apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-06-21T12:56:21Z"
  labels:
    app: istio-egressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: egressgateway
    istio.io/rev: default
    operator.istio.io/component: EgressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.22.1
    release: istio
  name: istio-egressgateway
  namespace: istio-system
  resourceVersion: "39905"
  uid: eb8268c8-217f-45f4-8fc2-f9ab60f87c18
spec:
  clusterIP: 10.96.225.133
  clusterIPs:
  - 10.96.225.133
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: istio-egressgateway
    istio: egressgateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
