apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.22.1
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 31665
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 32464
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31014
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 32664
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 32497
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort